version: "3.7"
services:
  db:
    build: .
    restart: always
    ports:
      - "127.0.0.1:${POSTGRES_LOCAL_PORT}:5432"
    # See .example_env for required environment variables.
    env_file: .env
    volumes:
      - db_volume:/var/lib/postgresql/data
      - type: bind
        source: ${IMPORT_DATA_DIR:-./example_data}
        target: /data
        read_only: true
volumes:
  db_volume:
