---
# Compose file for test runs
version: "3.8"
services:
  db:
    image: datarttu/sujuikodb:latest
    build: .
    restart: "no"
    env_file: .env_test
    volumes:
      - type: bind
        source: ./db/db_test
        target: /docker-entrypoint-initdb.d/
        read_only: true
      - type: tmpfs
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q"]
      interval: 30s
      start_period: 5s
      timeout: 20s
      retries: 3
  dataimporter:
    image: datarttu/sujuikodb:latest
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    volumes:
      - type: bind
        source: ${IMPORT_DATA_DIR}
        target: /data
        read_only: true
    env_file: .env_test
    # TODO: See if there is a better way to prevent dataimporter from
    #       trying imports before db is ready.
    #       Can we utilize healthcheck of db
    #       like docker-compose < v3 depends_on condition can do?
    command: |
      sh -c "
        psql -v ON_ERROR_STOP=on -f /data/import.sql
        status=\"$$?\"
        psql -c \"COPY (SELECT 1) TO PROGRAM 'pg_ctl stop --mode=smart --no-wait';\"
        exit \"$${status}\"
      "
