---
# Compose file for test runs
version: "3.8"
services:
  db_test:
    image: datarttu/sujuikodb:latest
    build: .
    restart: "no"
    env_file: .env_test
    volumes:
      - type: bind
        source: ./db
        target: /docker-entrypoint-initdb.d/
        read_only: true
      - type: tmpfs
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q"]
      interval: 5s
      start_period: 5s
      timeout: 20s
      retries: 3
    networks:
      - sujuikodb_test
  dataimporter_test:
    image: datarttu/sujuikodb:latest
    depends_on:
      db_test:
        condition: service_healthy
    restart: "no"
    volumes:
      - type: bind
        source: ./example_data
        target: /data
        read_only: true
    env_file: .env_test
    command: |
      sh -c "
        psql -1 -v ON_ERROR_STOP=on -f /data/import.sql
        status=\"$$?\"
        psql -c \"COPY (SELECT 1) TO PROGRAM 'pg_ctl stop --mode=smart --no-wait';\"
        exit \"$${status}\"
      "
    networks:
      - sujuikodb_test
networks:
  sujuikodb_test: {}
