version: "3.7"
services:
  sujuiko-db:
    build: .
    container_name: sujuiko-db
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
    ports:
      # NOTE: using 5435 here to avoid conflict with host machine 5432
      - 127.0.0.1:5435:5432
    # You will need POSTGRES_PASSWORD=something
    env_file: .env
volumes:
  dbdata:
