CREATE EXTENSION IF NOT EXISTS btree_gist CASCADE;
CREATE EXTENSION IF NOT EXISTS postgis CASCADE;
CREATE EXTENSION IF NOT EXISTS pgrouting CASCADE;
CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

CREATE FUNCTION append_unique(anyarray, anyelement)
RETURNS anyarray
IMMUTABLE
PARALLEL SAFE
LANGUAGE SQL
AS $$
  SELECT CASE
    WHEN ARRAY[$2] <@ $1 THEN $1
    ELSE array_append($1, $2)
  END;
$$;
